[package]
name = "vidcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
crossterm = "0.22.1"
ctrlc = "3.2.1"